baseurl = "https://blognilly.emperror.repl.co/"
disablePathToLower = false
languageCode = "en-us"
title = "Blog Do Nilly"
theme = "Hugo-Octopress"

# Disqus shortcode
# Disable comments for any individual post by adding "comments: false" in its frontmatter
disqusShortname = "O melhor do linux"

# Number of blog posts in each pagination page
paginate = 12

[permalinks]
# Configures post URLs
post = "/blog/:year-:month-:day-:title/"

[params]

  github = "https://github.com/nillythel0l/"
  # If false, all contents of posts will appear on the front page and in pagination
  truncate = true

  navigationNewWindow = true

  # Author's name (appears in meta tags and under posts)
  author = "NillyTheL0L"

  # This text appears in site header under website title
  subtitle = "O Melhor do linux"

  # Search engine URL
  searchEngineURL = ""

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Ler mais &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-XXXXX-X"

  # Optional piwik tracking
  #[params.analytics.piwik]
  #  URL = "https://stats.example.com"
  #  ID = "42"

  # Switch to true to enable RSS icon link
  rss = false

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  description = "O Melhor do linux"

  # Populate with your search keywords - these will appear in meta tags
  defaultKeywords = ["linuxbrasil" , "linux" , "linuxbr" , "bloglinux"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or set to false to use local fonts
  remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise, the theme uses ForkAwesome local fonts.
  fontAwesome = false

[markup]
  [markup.tableOfContents]
    endLevel = 8
    startLevel = 1
  [markup.highlight]
    style = "solarized-dark"

[[menu.main]]
  Name = "home"
  URL = "/"
  weight = -10

[[menu.main]]
  Name = "github"
  URL = "https://github.com/nillythel0l"
  weight = -5
